### ISSUE TITLE
Add Manual Refresh if stream is paused.

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleView#1]
From https://github.com/speckleworks/SpeckleRhino/issues/146

**Comment by fraguada** [comment]
![manualupdate](https://user-images.githubusercontent.com/1014562/37873474-f5b07d7c-301d-11e8-8731-dfda4832f354.gif)

**Comment by didimitrie** [comment]
@fraguada don't remember what's the status on this one? justa ping!

**Comment by didimitrie** [comment]
right, this one's getting closed as, weirdly enough, we forgot to do so: in a different form, @fraguada did add the stream refresh when a receiver is expired!
