### ISSUE TITLE
Replace vulnerable packages

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleView#6]
Running `npm install` today I get some warnings:

> npm WARN notice [SECURITY] sshpk has 1 high vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=sshpk&version=1.13.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
> npm WARN notice [SECURITY] stringstream has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=stringstream&version=0.0.5 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
> npm WARN notice [SECURITY] randomatic has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=randomatic&version=1.1.7 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
> npm WARN notice [SECURITY] macaddress has 1 critical vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=macaddress&version=0.2.8 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
> npm WARN notice [SECURITY] hoek has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=4.2.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

Also saw this when arriving in this repo today:
<img width="1135" alt="screen shot 2018-05-18 at 13 46 15" src="https://user-images.githubusercontent.com/1014562/40233178-3ad7104c-5aa2-11e8-8b82-2abf8ca54acd.png">

Are these critical packages to the way SpeckleView operates?

**Comment by didimitrie** [comment]
all these should not be a problem as we're running this ui locally. they will get remove once we get to actually do #15 and update everything...
